const mongoose = require ("mongoose");
const { boolean } = require("yargs");

const industrialPropertySchema = new mongoose.Schema(
    {
        lenguage: {type: String},
        h1ES: {type: String},
        descripcionInterna: {type: String},
        fuenteOriginal: {type: String},
        observaciones: {type: String},
        claveOriginal: {type: String},
        inmobiliaria: {type: String},
        agenteOriginal: {type: String},
        idioma: {type: String},
        status:{type: Boolean, deafault: false},
        pais: {type: String},
        ciudad: {type: String},
        colonia: {type: String},
        categoria: {type: String},
        urlEs: {type: String},
        urlCountry: {type: String},
        urlProvince: {type: String},
        urlCity: {type: String},
        titleTagEs: {type: String},
        metaDescEs: {type: String},
        keyWordsEs: {type: String},
        descripcionLarga: {type: String},
        videos: {type: String},
        posicionListado: {type: String},
        anoConstruccion: {type: String},
        usoSuelo: {type: String},
        m2Terreno: {type: String},
        m2Construcion: {type: String},
        precioString: {type: String},
        precio: {type: Number},
        precioM2: {type: String},
        altura: {type: String},
        frente: {type: String},
        fondo: {type: String},
        rampas: {type: String},
        andenes: {type: String},
        oficinas: {type: String},
        estacionamineto: {type: String},
        electricidad: {type: String},
        agua: {type: String},
        gasNatural: {type: String},
        plantaTratamiento: {type: String},
        areas: {type: String},
        acabados: {type: String},
        equipo: {type: String},
        otros: {type: String},
        costoMantenimiento: {type: String},
        constoVigilancia: {type: String},
        costoPredial: {type: String},
        atractivosCerca: {type: String},
        tiendasCerca: {type: String},
        direccion: {type: String},
        ubicacionGps: {type: String},
        telefono: {type: String},
        whatsApp: {type: Number},
        email: {type: String},
        restricciones: {type: String},
        landingUrl: {type: String},
        compartirRedes: {type: String},
        imgRoute: {type: String}
    },
    {timestamps:true}
)
module.exports = mongoose.model("IndustrialProperty", industrialPropertySchema )