const mongoose = require ("mongoose");

const propertySchema = new mongoose.Schema(
    {
        h1ES: {type: String},
        descripcionInterna: {type: String},
        fuenteOriginal: {type: String},
        observaciones: {type: String},
        claveOriginal: {type: String},
        inmobiliaria: {type: String},
        agenteOriginal: {type: String},
        idioma: {type: String},
        status:{type: Boolean, deafault: false},
        pais: {type: String},
        estado: {type: String},
        colonia: {type: String},
        categoria: {type: String},
        urlEs: {type: String},
        titleTagEs: {type: String},
        metaDescEs: {type: String},
        keyWordsEs: {type: String},
        descripcionLarga: {type: String},
        videos: {type: String},
        posicionListado: {type: String},
        añoConstruccion: {type: Number},
        usoSuelo: {type: String},
        m2Construcion: {type: Number},
        precioString: {type: String},
        precio: {type: Number},
        precioM2: {type: Number},
        estilo: {type: String},
        niveles: {type: Number},
        recamaras: {type: Number},
        closetsTipo: {type: String},
        baños: {type: Number},
        cuartoServicio: {type: String},
        estacionamineto: {type:string},
        jardinM2: {type: Number},
        orientacion: {type: String},
        areas: {type: String},
        acabados: {type: String},
        equipo: {type: String},
        otros: {type: String},
        costoMantenimiento: {type: Number},
        costoPredial: {type: Number},
        atractivosCerca: {type: String},
        escuelasCerca: {type: String},
        tiendasCerca: {type: String},
        direccion: {type: String},
        ubicacionGps: {type: String},
        teléfono: {type: Number},
        WhatsApp: {type: Number},
        email: {type: String},
        restricciones: {type: String},
        landingUrl: {type: String},
        compartirRedes: {type: String}
    },
    {timestamps:true}
)